### PR TITLE
PM-548: refactor mina daemon helm chart service naming

### PR DESCRIPTION
**Pull request by simisimis**

### CODE REVIEW

**Comment by Smorci** [comment]
I will approve this after [this ticket](https://minafoundation.atlassian.net/browse/PM-549?atlOrigin=eyJpIjoiNTBjODUyYWU0ZWFkNDAxNDkxZjk2OTY5MWVhYzJlMGIiLCJwIjoiaiJ9) is done

**Comment by kaozenn** [comment]
@simisimis , is this PR introducing any breaking changes in existing projects?

**Comment by simisimis** [comment]
> is this PR introducing any breaking changes in existing projects?

yes. Any project that is using `service` needs to be modified to use `service.daemon`. 
I have created prs for affected services.
https://github.com/MinaFoundation/gitops-staging/pull/113
https://github.com/MinaFoundation/gitops-production/pull/53

**Comment by kaozenn** [comment]
Thank you @simisimis , can we also cover https://github.com/MinaProtocol/gitops-partners/punkpoll?
I will look at merging the PR and ensure their Network keep running smoothly

**Comment by simisimis** [comment]
good catch did not look into partners folder, but now I checked it and I don't see you overriding there ClusterIP with LoadBalancer, so in that case no changes are needed there

**Review by kaozenn — APPROVED** [review]
Looks good to me

**Pull request merged**
