### PR TITLE
PM-1532 add raw helm chart to our helm charts

### PR DESCRIPTION
**Pull request by simisimis**
This chart is copied from archived now repository for us to be able to access it easier and not depend on it disappearing.
With this chart we can deploy in our releases loose additional k8s resources

### CODE REVIEW

**Review by kaozenn — APPROVED** [review]
Considering this is a copy / paste from the incubator repository, I think it is fine to merge as it is. However, the pre-commit will start to fail once all repositories are enabled.
We may need to review the value.yaml then

**Comment by Smorci** [comment]
> **Thought** Considering this is a copy / paste from the incubator repository, I think it is fine to merge as it is. However, the pre-commit will start to fail once all repositories are enabled. We may need to review the values.yaml then

**Suggestion:** @kaozenn if this chart breaks the pre-commit then we can use a [.helmdocsignore](https://github.com/norwoodj/helm-docs/blob/master/.helmdocsignore) file to ignore this

**Comment by simisimis** [comment]
I don't think there's much to do here with documentation. We should just not add this to pre-commit list of helm charts.
This chart has only two values in values.yaml `resources` and `templates`.
Unless something would change in the way helm is templating we would need to look into, otherwise nothing should change in this chart and I believe it's best leave it at that

**Comment by Smorci** [comment]
> We should just not add this to pre-commit list of helm charts.

At one point in time we will enable the pre-commit for all helm charts, and than it is easier to ignore.

**Review by Smorci — APPROVED** [review]
Looks good

**Comment by simisimis** [comment]
Because there's only 2 lines, we could just add `#--` for those 2 values and discard original README when time comes.

**Pull request merged**
